[theme]
primaryColor = "#4CAF50"       # Màu chính (ví dụ: xanh lá cây)
backgroundColor = "#FFFFFF"    # Màu nền
secondaryBackgroundColor = "#F0F2F6"  # Màu nền phụ (sidebar)
textColor = "#31333F"          # Màu chữ

